---
# This tasks will setup mariadb-server

  - name: Add MariaDB repository
    apt:
      name: "software-properties-common"
      update_cache: "no"
      state: "present"
  - apt_key:
      keyserver: "hkp://keyserver.ubuntu.com:80"
      id: "0xF1656F24C74CD1D8"
      state: "present"
  - apt_repository:
      repo: "deb [arch=amd64,i386,ppc64el] http://fr.mirror.babylon.network/mariadb/repo/10.1/ubuntu xenial main"
      state: "present"
      update_cache: "yes"

  - name: Install MariaDB
    apt:
      name: "mariadb-server-10.1"
      update_cache: "no"
      state: "present"

  - name: Install Galera
    apt:
      name: "galera"
      update_cache: "no"
      state: "present"