---
# This tasks are installing composer into /usr/local/bin recommanded path

  - name: Download composer
    get_url:
      url: "https://getcomposer.org/installer"
      dest: "/tmp/composer-installer"

  - name: Setup Composer
    shell: cat /tmp/composer-installer | php -- --install-dir=/usr/local/bin --filename=composer
    args:
      creates: /usr/local/bin/composer
    tags: composer