---
# The following tasks will seed the dbservers

  - name: Publish SeAT vendor packages
    command: /usr/bin/php artisan vendor:publish
    args:
      chdir: "/var/www/{{ item.name }}.eveseat.net/"
    become: true
    become_user: "{{ item.name }}"
    with_items: "{{ seat_tickers }}"

  - name: Run migration scripts and seed database
    command: /usr/bin/php artisan migrate
    args:
      chdir: "/var/www/{{ item.name }}.eveseat.net/"
    become: true
    become_user: "{{ item.name }}"
    with_items: seat_tickers
    when: ansible_fqdn == cluster_master_nodename

  - name: Seed database with notification types
    command: /usr/bin/php artisan db:seed --class=Seat\\Services\\database\\seeds\\NotificationTypesSeeder
    args:
      chdir: "/var/www/{{ item.name }}.eveseat.net/"
    become: true
    become_user: "{{ item.name }}"
    with_items: "{{ seat_tickers }}"
    when: ansible_fqdn == cluster_master_nodename

  - name: Seed database with schedulers
    command: /usr/bin/php artisan db:seed --class=Seat\\Services\\database\\seeds\\ScheduleSeeder
    args:
      chdir: "/var/www/{{ item.name }}.eveseat.net/"
    become: true
    become_user: "{{ item.name }}"
    with_items: "{{ seat_tickers }}"
    when: ansible_fqdn == cluster_master_nodename

  - name: update SDE
    command: /usr/bin/php artisan eve:update-sde -n
    args:
      chdir: "/var/www/{{ item.name }}.eveseat.net/"
    become: true
    become_user: "{{ item.name }}"
    with_items: "{{ seat_tickers }}"
    when: ansible_fqdn == cluster_master_nodename